### ISSUE TITLE
Automatic update date

### ISSUE THREAD

**Issue by ryales** [BrcMapsTeam/Europe_migrants_sitrep#58]
Minor point but annoying to have to remember to manually do every week. Is there a way you can input the most recent update date in the header for the migrant sitrep page? You could pull from the Austria date, as they never fail to update on a weekly basis.

**Comment by heidieh** [comment]
Done this - as suggested it is pulling the date from Austria, so you/someone might need to keep an eye on this. Also, month is in number format - if you want me to change this back to month name then let me know, its a little extra work but wasn't sure it was important.
